// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: metrics.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Interfaces    []*InterfaceMetrics    `protobuf:"bytes,5,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	CustomMetrics map[string]float64     `protobuf:"bytes,6,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReport) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsReport) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *MetricsReport) GetInterfaces() []*InterfaceMetrics {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *MetricsReport) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

type MetricsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsAck) Reset() {
	*x = MetricsAck{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsAck) ProtoMessage() {}

func (x *MetricsAck) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsAck.ProtoReflect.Descriptor instead.
func (*MetricsAck) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *MetricsAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type SystemMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent         float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent      float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryTotalBytes   int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes    int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,6,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	FirmwareVersion    string                 `protobuf:"bytes,7,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	BoardName          string                 `protobuf:"bytes,8,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemMetrics) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *SystemMetrics) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *SystemMetrics) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

type InterfaceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsUp          bool                   `protobuf:"varint,3,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	SpeedMbps     int64                  `protobuf:"varint,4,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	RxBytes       int64                  `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     int64                  `protobuf:"varint,7,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     int64                  `protobuf:"varint,8,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxErrors      int64                  `protobuf:"varint,9,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      int64                  `protobuf:"varint,10,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	RxDrops       int64                  `protobuf:"varint,11,opt,name=rx_drops,json=rxDrops,proto3" json:"rx_drops,omitempty"`
	TxDrops       int64                  `protobuf:"varint,12,opt,name=tx_drops,json=txDrops,proto3" json:"tx_drops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceMetrics) Reset() {
	*x = InterfaceMetrics{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceMetrics) ProtoMessage() {}

func (x *InterfaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceMetrics.ProtoReflect.Descriptor instead.
func (*InterfaceMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceMetrics) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InterfaceMetrics) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *InterfaceMetrics) GetSpeedMbps() int64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *InterfaceMetrics) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetRxPackets() int64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetTxPackets() int64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetRxErrors() int64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *InterfaceMetrics) GetTxErrors() int64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *InterfaceMetrics) GetRxDrops() int64 {
	if x != nil {
		return x.RxDrops
	}
	return 0
}

func (x *InterfaceMetrics) GetTxDrops() int64 {
	if x != nil {
		return x.TxDrops
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x13ispmonitor.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x03\n" +
	"\rMetricsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12:\n" +
	"\x06system\x18\x04 \x01(\v2\".ispmonitor.agent.v1.SystemMetricsR\x06system\x12E\n" +
	"\n" +
	"interfaces\x18\x05 \x03(\v2%.ispmonitor.agent.v1.InterfaceMetricsR\n" +
	"interfaces\x12\\\n" +
	"\x0ecustom_metrics\x18\x06 \x03(\v25.ispmonitor.agent.v1.MetricsReport.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"C\n" +
	"\n" +
	"MetricsAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\"\xd3\x02\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12/\n" +
	"\x13temperature_celsius\x18\x06 \x01(\x01R\x12temperatureCelsius\x12)\n" +
	"\x10firmware_version\x18\a \x01(\tR\x0ffirmwareVersion\x12\x1d\n" +
	"\n" +
	"board_name\x18\b \x01(\tR\tboardName\"\xe0\x02\n" +
	"\x10InterfaceMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x13\n" +
	"\x05is_up\x18\x03 \x01(\bR\x04isUp\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x04 \x01(\x03R\tspeedMbps\x12\x19\n" +
	"\brx_bytes\x18\x05 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x06 \x01(\x03R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\a \x01(\x03R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\b \x01(\x03R\ttxPackets\x12\x1b\n" +
	"\trx_errors\x18\t \x01(\x03R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\n" +
	" \x01(\x03R\btxErrors\x12\x19\n" +
	"\brx_drops\x18\v \x01(\x03R\arxDrops\x12\x19\n" +
	"\btx_drops\x18\f \x01(\x03R\atxDropsBHZFgithub.com/MohamadKhaledAbbas/ISPVisualMonitor-Agent/api/proto/agentpbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metrics_proto_goTypes = []any{
	(*MetricsReport)(nil),         // 0: ispmonitor.agent.v1.MetricsReport
	(*MetricsAck)(nil),            // 1: ispmonitor.agent.v1.MetricsAck
	(*SystemMetrics)(nil),         // 2: ispmonitor.agent.v1.SystemMetrics
	(*InterfaceMetrics)(nil),      // 3: ispmonitor.agent.v1.InterfaceMetrics
	nil,                           // 4: ispmonitor.agent.v1.MetricsReport.CustomMetricsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	5, // 0: ispmonitor.agent.v1.MetricsReport.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: ispmonitor.agent.v1.MetricsReport.system:type_name -> ispmonitor.agent.v1.SystemMetrics
	3, // 2: ispmonitor.agent.v1.MetricsReport.interfaces:type_name -> ispmonitor.agent.v1.InterfaceMetrics
	4, // 3: ispmonitor.agent.v1.MetricsReport.custom_metrics:type_name -> ispmonitor.agent.v1.MetricsReport.CustomMetricsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
