// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sessions.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PppoeSessions []*PPPoESession        `protobuf:"bytes,4,rep,name=pppoe_sessions,json=pppoeSessions,proto3" json:"pppoe_sessions,omitempty"`
	NatSessions   []*NATSession          `protobuf:"bytes,5,rep,name=nat_sessions,json=natSessions,proto3" json:"nat_sessions,omitempty"`
	DhcpLeases    []*DHCPLease           `protobuf:"bytes,6,rep,name=dhcp_leases,json=dhcpLeases,proto3" json:"dhcp_leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReport) Reset() {
	*x = SessionReport{}
	mi := &file_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReport) ProtoMessage() {}

func (x *SessionReport) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReport.ProtoReflect.Descriptor instead.
func (*SessionReport) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *SessionReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionReport) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *SessionReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionReport) GetPppoeSessions() []*PPPoESession {
	if x != nil {
		return x.PppoeSessions
	}
	return nil
}

func (x *SessionReport) GetNatSessions() []*NATSession {
	if x != nil {
		return x.NatSessions
	}
	return nil
}

func (x *SessionReport) GetDhcpLeases() []*DHCPLease {
	if x != nil {
		return x.DhcpLeases
	}
	return nil
}

type SessionReportResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionsProcessed int32                  `protobuf:"varint,2,opt,name=sessions_processed,json=sessionsProcessed,proto3" json:"sessions_processed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionReportResponse) Reset() {
	*x = SessionReportResponse{}
	mi := &file_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReportResponse) ProtoMessage() {}

func (x *SessionReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReportResponse.ProtoReflect.Descriptor instead.
func (*SessionReportResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *SessionReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionReportResponse) GetSessionsProcessed() int32 {
	if x != nil {
		return x.SessionsProcessed
	}
	return 0
}

type PPPoESession struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CallingStationId   string                 `protobuf:"bytes,3,opt,name=calling_station_id,json=callingStationId,proto3" json:"calling_station_id,omitempty"`
	FramedIp           string                 `protobuf:"bytes,4,opt,name=framed_ip,json=framedIp,proto3" json:"framed_ip,omitempty"`
	SessionTimeSeconds int64                  `protobuf:"varint,5,opt,name=session_time_seconds,json=sessionTimeSeconds,proto3" json:"session_time_seconds,omitempty"`
	BytesIn            int64                  `protobuf:"varint,6,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut           int64                  `protobuf:"varint,7,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ConnectTime        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PPPoESession) Reset() {
	*x = PPPoESession{}
	mi := &file_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPPoESession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPPoESession) ProtoMessage() {}

func (x *PPPoESession) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPPoESession.ProtoReflect.Descriptor instead.
func (*PPPoESession) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *PPPoESession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PPPoESession) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PPPoESession) GetCallingStationId() string {
	if x != nil {
		return x.CallingStationId
	}
	return ""
}

func (x *PPPoESession) GetFramedIp() string {
	if x != nil {
		return x.FramedIp
	}
	return ""
}

func (x *PPPoESession) GetSessionTimeSeconds() int64 {
	if x != nil {
		return x.SessionTimeSeconds
	}
	return 0
}

func (x *PPPoESession) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *PPPoESession) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *PPPoESession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PPPoESession) GetConnectTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectTime
	}
	return nil
}

type NATSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Protocol          string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SrcAddress        string                 `protobuf:"bytes,2,opt,name=src_address,json=srcAddress,proto3" json:"src_address,omitempty"`
	SrcPort           int32                  `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstAddress        string                 `protobuf:"bytes,4,opt,name=dst_address,json=dstAddress,proto3" json:"dst_address,omitempty"`
	DstPort           int32                  `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	TranslatedAddress string                 `protobuf:"bytes,6,opt,name=translated_address,json=translatedAddress,proto3" json:"translated_address,omitempty"`
	TranslatedPort    int32                  `protobuf:"varint,7,opt,name=translated_port,json=translatedPort,proto3" json:"translated_port,omitempty"`
	Bytes             int64                  `protobuf:"varint,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets           int64                  `protobuf:"varint,9,opt,name=packets,proto3" json:"packets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NATSession) Reset() {
	*x = NATSession{}
	mi := &file_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NATSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NATSession) ProtoMessage() {}

func (x *NATSession) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NATSession.ProtoReflect.Descriptor instead.
func (*NATSession) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *NATSession) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NATSession) GetSrcAddress() string {
	if x != nil {
		return x.SrcAddress
	}
	return ""
}

func (x *NATSession) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NATSession) GetDstAddress() string {
	if x != nil {
		return x.DstAddress
	}
	return ""
}

func (x *NATSession) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NATSession) GetTranslatedAddress() string {
	if x != nil {
		return x.TranslatedAddress
	}
	return ""
}

func (x *NATSession) GetTranslatedPort() int32 {
	if x != nil {
		return x.TranslatedPort
	}
	return 0
}

func (x *NATSession) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *NATSession) GetPackets() int64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

type DHCPLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LeaseStart    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_start,json=leaseStart,proto3" json:"lease_start,omitempty"`
	LeaseEnd      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lease_end,json=leaseEnd,proto3" json:"lease_end,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHCPLease) Reset() {
	*x = DHCPLease{}
	mi := &file_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHCPLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHCPLease) ProtoMessage() {}

func (x *DHCPLease) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHCPLease.ProtoReflect.Descriptor instead.
func (*DHCPLease) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *DHCPLease) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DHCPLease) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DHCPLease) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DHCPLease) GetLeaseStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseStart
	}
	return nil
}

func (x *DHCPLease) GetLeaseEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseEnd
	}
	return nil
}

func (x *DHCPLease) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_sessions_proto protoreflect.FileDescriptor

const file_sessions_proto_rawDesc = "" +
	"\n" +
	"\x0esessions.proto\x12\x13ispmonitor.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\rSessionReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x0epppoe_sessions\x18\x04 \x03(\v2!.ispmonitor.agent.v1.PPPoESessionR\rpppoeSessions\x12B\n" +
	"\fnat_sessions\x18\x05 \x03(\v2\x1f.ispmonitor.agent.v1.NATSessionR\vnatSessions\x12?\n" +
	"\vdhcp_leases\x18\x06 \x03(\v2\x1e.ispmonitor.agent.v1.DHCPLeaseR\n" +
	"dhcpLeases\"`\n" +
	"\x15SessionReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12sessions_processed\x18\x02 \x01(\x05R\x11sessionsProcessed\"\xd5\x02\n" +
	"\fPPPoESession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12,\n" +
	"\x12calling_station_id\x18\x03 \x01(\tR\x10callingStationId\x12\x1b\n" +
	"\tframed_ip\x18\x04 \x01(\tR\bframedIp\x120\n" +
	"\x14session_time_seconds\x18\x05 \x01(\x03R\x12sessionTimeSeconds\x12\x19\n" +
	"\bbytes_in\x18\x06 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\a \x01(\x03R\bbytesOut\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12=\n" +
	"\fconnect_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vconnectTime\"\xa8\x02\n" +
	"\n" +
	"NATSession\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vsrc_address\x18\x02 \x01(\tR\n" +
	"srcAddress\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\x05R\asrcPort\x12\x1f\n" +
	"\vdst_address\x18\x04 \x01(\tR\n" +
	"dstAddress\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\x05R\adstPort\x12-\n" +
	"\x12translated_address\x18\x06 \x01(\tR\x11translatedAddress\x12'\n" +
	"\x0ftranslated_port\x18\a \x01(\x05R\x0etranslatedPort\x12\x14\n" +
	"\x05bytes\x18\b \x01(\x03R\x05bytes\x12\x18\n" +
	"\apackets\x18\t \x01(\x03R\apackets\"\xf5\x01\n" +
	"\tDHCPLease\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12;\n" +
	"\vlease_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"leaseStart\x127\n" +
	"\tlease_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bleaseEnd\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06statusBHZFgithub.com/MohamadKhaledAbbas/ISPVisualMonitor-Agent/api/proto/agentpbb\x06proto3"

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData []byte
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)))
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sessions_proto_goTypes = []any{
	(*SessionReport)(nil),         // 0: ispmonitor.agent.v1.SessionReport
	(*SessionReportResponse)(nil), // 1: ispmonitor.agent.v1.SessionReportResponse
	(*PPPoESession)(nil),          // 2: ispmonitor.agent.v1.PPPoESession
	(*NATSession)(nil),            // 3: ispmonitor.agent.v1.NATSession
	(*DHCPLease)(nil),             // 4: ispmonitor.agent.v1.DHCPLease
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_sessions_proto_depIdxs = []int32{
	5, // 0: ispmonitor.agent.v1.SessionReport.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: ispmonitor.agent.v1.SessionReport.pppoe_sessions:type_name -> ispmonitor.agent.v1.PPPoESession
	3, // 2: ispmonitor.agent.v1.SessionReport.nat_sessions:type_name -> ispmonitor.agent.v1.NATSession
	4, // 3: ispmonitor.agent.v1.SessionReport.dhcp_leases:type_name -> ispmonitor.agent.v1.DHCPLease
	5, // 4: ispmonitor.agent.v1.PPPoESession.connect_time:type_name -> google.protobuf.Timestamp
	5, // 5: ispmonitor.agent.v1.DHCPLease.lease_start:type_name -> google.protobuf.Timestamp
	5, // 6: ispmonitor.agent.v1.DHCPLease.lease_end:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}
