// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: license.proto

package licensepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey          string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	AgentId             string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HardwareFingerprint string                 `protobuf:"bytes,3,opt,name=hardware_fingerprint,json=hardwareFingerprint,proto3" json:"hardware_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_license_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_license_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_license_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *ValidateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ValidateRequest) GetHardwareFingerprint() string {
	if x != nil {
		return x.HardwareFingerprint
	}
	return ""
}

type ValidateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Valid           bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Tier            string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxRouters      int32                  `protobuf:"varint,4,opt,name=max_routers,json=maxRouters,proto3" json:"max_routers,omitempty"`
	EnabledFeatures []string               `protobuf:"bytes,5,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_license_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_license_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_license_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *ValidateResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateResponse) GetMaxRouters() int32 {
	if x != nil {
		return x.MaxRouters
	}
	return 0
}

func (x *ValidateResponse) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_license_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_license_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_license_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *RefreshRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NextRefresh   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_refresh,json=nextRefresh,proto3" json:"next_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_license_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_license_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_license_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshResponse) GetNextRefresh() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRefresh
	}
	return nil
}

var File_license_proto protoreflect.FileDescriptor

const file_license_proto_rawDesc = "" +
	"\n" +
	"\rlicense.proto\x12\x15ispmonitor.license.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x0fValidateRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x121\n" +
	"\x14hardware_fingerprint\x18\x03 \x01(\tR\x13hardwareFingerprint\"\xdd\x01\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vmax_routers\x18\x04 \x01(\x05R\n" +
	"maxRouters\x12)\n" +
	"\x10enabled_features\x18\x05 \x03(\tR\x0fenabledFeatures\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"L\n" +
	"\x0eRefreshRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"j\n" +
	"\x0fRefreshResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\fnext_refresh\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vnextRefresh2\xd5\x01\n" +
	"\x0eLicenseService\x12b\n" +
	"\x0fValidateLicense\x12&.ispmonitor.license.v1.ValidateRequest\x1a'.ispmonitor.license.v1.ValidateResponse\x12_\n" +
	"\x0eRefreshLicense\x12%.ispmonitor.license.v1.RefreshRequest\x1a&.ispmonitor.license.v1.RefreshResponseBJZHgithub.com/MohamadKhaledAbbas/ISPVisualMonitor-Agent/api/proto/licensepbb\x06proto3"

var (
	file_license_proto_rawDescOnce sync.Once
	file_license_proto_rawDescData []byte
)

func file_license_proto_rawDescGZIP() []byte {
	file_license_proto_rawDescOnce.Do(func() {
		file_license_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_license_proto_rawDesc), len(file_license_proto_rawDesc)))
	})
	return file_license_proto_rawDescData
}

var file_license_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_license_proto_goTypes = []any{
	(*ValidateRequest)(nil),       // 0: ispmonitor.license.v1.ValidateRequest
	(*ValidateResponse)(nil),      // 1: ispmonitor.license.v1.ValidateResponse
	(*RefreshRequest)(nil),        // 2: ispmonitor.license.v1.RefreshRequest
	(*RefreshResponse)(nil),       // 3: ispmonitor.license.v1.RefreshResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_license_proto_depIdxs = []int32{
	4, // 0: ispmonitor.license.v1.ValidateResponse.expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: ispmonitor.license.v1.RefreshResponse.next_refresh:type_name -> google.protobuf.Timestamp
	0, // 2: ispmonitor.license.v1.LicenseService.ValidateLicense:input_type -> ispmonitor.license.v1.ValidateRequest
	2, // 3: ispmonitor.license.v1.LicenseService.RefreshLicense:input_type -> ispmonitor.license.v1.RefreshRequest
	1, // 4: ispmonitor.license.v1.LicenseService.ValidateLicense:output_type -> ispmonitor.license.v1.ValidateResponse
	3, // 5: ispmonitor.license.v1.LicenseService.RefreshLicense:output_type -> ispmonitor.license.v1.RefreshResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_license_proto_init() }
func file_license_proto_init() {
	if File_license_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_license_proto_rawDesc), len(file_license_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_license_proto_goTypes,
		DependencyIndexes: file_license_proto_depIdxs,
		MessageInfos:      file_license_proto_msgTypes,
	}.Build()
	File_license_proto = out.File
	file_license_proto_goTypes = nil
	file_license_proto_depIdxs = nil
}
